<div>
    <table border="1">
        <thead>
            <th>Nome</th>
            <th>Email</th>
            <th>Telefone</th>
            <th>Fax</th>
            <th>Address Count</th>
        </thead>
        <?php foreach($this->resultado as $usuarios): ?>
            <tr>
                <td><?php echo $usuarios->getUsername(); ?></td>
                <td><?php echo $usuarios->getEmail(); ?></td>
                <td><?php echo $usuarios->getPhone(); ?></td>
                <td><?php echo $usuarios->getFax(); ?></td>
                <td><?php if($usuarios->getTypeId() == 1){ echo "Home address"; } else { echo "Billing address"; } ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
</div>